export enum NotificationEventType {
    OTP_SEND = "OTP_SEND",
    USER_CREATE = "USER_CREATE",
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
    PAYMENT_FAILED = "PAYMENT_FAILED",
    BOOKING_CREATED= "BOOKING_CREATED",
    BOOKING_CONFIRMED="BOOKING_CONFIRMED",
    BOOKING_CANCELLED="BOOKING_CANCELLED",

}